version: "3.8"

volumes:
  user-mysql-data:
    driver: local
  user-mysql-logs:
    driver: local

networks:
  spick-net:
    driver: bridge
    external: true

services:
  user-mysql:
    networks:
      - spick-net
    image: user-mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p root",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
  
   

    ###############################################
    # callbook: The test_invoke_http.py program
    ###############################################
  user:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spick-net
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+mysqlconnector://root:password@user-mysql:3306/user
    ports:
      - "8001:8001"
    depends_on:
      user-mysql:
        condition: service_healthy
